language: node_js
notifications:
  email: false
cache:
  directories:
  - "$HOME/.npm"
jobs:
  include:
  - stage: test
    script:
    - npm run lint
    - npm test
    - npm run coverage
  - stage: deploy
    install: true
    if: branch = release/demo
    script:
    - echo 'Deploying to NOW'
    - npm install -g now
    - npm run deploy-demo && npm run alias-demo
  - stage: deploy
    install: true
    if: branch = release/playground
    script:
    - echo 'Deploying to NOW'
    - npm install -g now
    - npm run deploy-playground && npm run alias-playground
env:
  global:
    secure: eDqM+qO8M/VrtvRBTh9O3IG7Ab5dhHfSQaMgC/imaiy0MUxK6wCE7WPQ12Fd3ULw2l+EFM0l9gcPeSINzZz+hVxZ2CUlGw6FUVqvawbuR0wx/xWXsIKGyq/43w6mojbZ8rhy4DNiD9J/gSrYDQ+pdL72GUfQ+QtGQt/wTov2Qmac8tlVCVSoSAiBj632hLkwsYPJM1Jj6WM+6SuYKk8C/5nIC9gPkx+8EZDC5hQtcdyrzxn/gM76SQ3SLT4vpyhebcbQlGPL+F/gei3IgHAAjZcAMEg5LOVr23ByOclZBB1po1dwu2/aNVI113aaXvIx+68H1aTksL261vxODq2bObF0joeOAERPWRFBHofDWugUzwudhl0BXTXgzDtxvdONKzFQlZUrBV17i3dOk5gkIUraCqMNrsTnPbZTWoa23CaI1MeBZxOuaFnMJXtNU+XiMo8cG20h554Yq3P4mLdkQLMhZyCsZjNKNVvmCeYYGEBvbYpos83WX0RxSmw3qEnB+u76TjGPmUgrIxIfudwDfP6QQdISZtODhCVDeCzS8FJczuQLrhTsNXWGsu9gIVzXq2TnfHUJMYV1QQXmiYDcsdjKELl5OK1+YrlCiGCi9bifrxaMkQq4TODA+dZKBS7LC7mZ172T0zg/E+42WRae+Pbc4gEd7LwxpjNUVRUu2pM=
